package com.proyectoiub.gui;

import com.proyectoiub.entidades.*;
import com.proyectoiub.infraestructure.*;
import com.proyectoiub.servicios.*;
import javax.swing.*;
import java.util.List;

public class InscripcionGui extends javax.swing.JFrame {

    private JFrame parent;
    
    public InscripcionGui(JFrame parent) {
        initComponents();
        cargarCursos();
        cargarEstudiante();
        
        this.parent = parent;
        
        setTitle("Horario");
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (parent != null) {
                    parent.setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lstCurso = new javax.swing.JComboBox();
        lstEstudiante = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Inscripción");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Estudiante");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Curso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lstCurso, 0, 150, Short.MAX_VALUE)
                            .addComponent(lstEstudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnGuardar)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lstEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lstCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnGuardar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarEstudiante() {
        try {
            DatabaseConfig dbConfig = new DatabaseConfig();
            var estudianteDao = dbConfig.getEstudianteDao();

            List<Estudiante> lista = estudianteDao.queryForAll();

            List<ComboUtils.Item> items =
                ComboUtils.map(lista, "nombre");

            lstEstudiante.setModel(new DefaultComboBoxModel<>(items.toArray()));
            lstEstudiante.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    private void cargarCursos() {
        try {
            DatabaseConfig dbConfig = new DatabaseConfig();
            var cursoDao = dbConfig.getCursoDao();

            List<Curso> lista = cursoDao.queryForAll();

            List<ComboUtils.Item> items =
                ComboUtils.map(lista, "nombreCurso");

            lstCurso.setModel(new DefaultComboBoxModel<>(items.toArray()));
            lstCurso.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    public void limpiarCampos(){
        lstCurso.setSelectedIndex(-1);
        lstEstudiante.setSelectedIndex(-1);
         
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            ComboUtils.Item itemCurso = (ComboUtils.Item) lstCurso.getSelectedItem();
            if (itemCurso == null) {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un curso");
                lstCurso.requestFocus();
                return;
            }

            ComboUtils.Item itemEstudiante = (ComboUtils.Item) lstEstudiante.getSelectedItem();
            if (itemEstudiante == null) {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un estudiante");
                lstEstudiante.requestFocus();
                return;
            }

            DatabaseConfig dbConfig = new DatabaseConfig();
            var cursoDao = dbConfig.getCursoDao();
            var estudianteDao = dbConfig.getEstudianteDao();
            var cursoestDao = dbConfig.getCursoestDao();

            Curso curso = cursoDao.queryForId(itemCurso.getId());
            Estudiante estudiante = estudianteDao.queryForId(itemEstudiante.getId());

            List<CursoEstudiante> lista = cursoestDao.queryForAll();
            for (CursoEstudiante ce : lista) {
                if (ce.getCurso().getIdCurso().equals(curso.getIdCurso()) &&
                    ce.getEstudiante().getIdentificacion().equals(estudiante.getIdentificacion())) {

                    JOptionPane.showMessageDialog(rootPane, "El estudiante ya está inscrito en este curso");
                    return;
                }
            }

            CursoEstudiante cursoEst = new CursoEstudiante();
            cursoEst.setCurso(curso);
            cursoEst.setEstudiante(estudiante);

            cursoestDao.create(cursoEst);

            JOptionPane.showMessageDialog(rootPane, "Inscripción guardada con éxito!");
            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,
                    "Se ha producido una excepción: " + ex.getMessage(),
                    "Alerta",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscripcionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscripcionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscripcionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscripcionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionGui(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox lstCurso;
    private javax.swing.JComboBox lstEstudiante;
    // End of variables declaration//GEN-END:variables
}
